BOTWRecipeEngine/Models/Botw_Recipes.cs
namespace BOTWRecipeEngine.Models
{
    public class Botw_Recipes
    {
        public int ID { get; set; }

        public string RecipeName { get; set; }

        public string Ingredient1 { get; set; }

        public string Ingredient2 { get; set; }

        public string Ingredient3 { get; set; }

        public string Ingredient4 { get; set; }

        public string Num_Hearts { get; set; }

        public string RecipePicture { get; set; }
    }
}

BOTWRecipeEngine/Models/ErrorViewModel.cs
namespace BOTWRecipeEngine.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BOTWRecipeEngine/Models/Recipe.cs
using System.ComponentModel.DataAnnotations;

namespace BOTWRecipeEngine.Models
{
    public class Botw_Recipes
    {
        public int ID { get; set; }

        public string RecipeName { get; set; }

        public string Ingredient1 { get; set; } // TODO: Determine how to handle multiple ingredients

        public string Ingredient2 { get; set; }

        public string Ingredient3 { get; set; }

        public string Ingredient4 { get; set; }

        public string Num_Hearts { get; set; }

        public string RecipePicture { get; set; }
    }
}

BOTWRecipeEngine/Controllers/HomeController.cs
using Azure;
using BOTWRecipeEngine.Data;
using BOTWRecipeEngine.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace BOTWRecipeEngine.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly RecipeContext _context;

        public HomeController(ILogger<HomeController> logger, RecipeContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            List<Botw_Recipes> model = _context.Recipes.ToList();
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BOTWRecipeEngine/Controllers/RecipeController.cs
using BOTWRecipeEngine.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BOTWRecipeEngine.Controllers
{
    public class RecipeController : Controller
    {
        private readonly RecipeContext _context;
        public RecipeController(RecipeContext context)
        {
            _context = context;
        }
        // GET: RecipeController
        public async Task<IActionResult> Index()
        {
            return View(await _context.Recipes.ToListAsync());
        }

        // GET: RecipeController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RecipeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RecipeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RecipeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RecipeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RecipeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RecipeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BOTWRecipeEngine/Views/Home/Index.cshtml
@model List<Botw_Recipes>;

@{
    ViewData["Title"] = "Breath of the Wild Recipe Engine";
}

<h1>Breath of the Wild Recipe Engine</h1>

<p class="Welcome">
    Welcome to the Breath of the Wild Recipe Engine!
</p>

<p class="Welcome2">
    Down below you can select an ingredient in each drop down menu, then when
    you have selected your ingredients you can generate the recipe to see how many hearts the recipe gives you,
    any stat bonuses the recipe may have, along with the recipe name and picture!
</p>


<div class="row">
    <div class="col-md-12 text-center">
        <div class="btn-group-vertical" role="group">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Ingredient 1
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item1">Fortified Pumpkin</a></li>
                    <li><a class="dropdown-item2">Goat Butter</a></li>
                    <li><a class="dropdown-item3">Fresh Milk</a></li>
                    <li><a class="dropdown-item4">Tabantha Wheat</a></li>
                </ul>
            </div>

            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Ingredient 2
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item1">Fortified Pumpkin</a></li>
                    <li><a class="dropdown-item2">Goat Butter</a></li>
                    <li><a class="dropdown-item3">Fresh Milk</a></li>
                    <li><a class="dropdown-item4">Tabantha Wheat</a></li>
                </ul>
            </div>

            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Ingredient 3
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item1">Fortified Pumpkin</a></li>
                    <li><a class="dropdown-item2">Goat Butter</a></li>
                    <li><a class="dropdown-item3">Fresh Milk</a></li>
                    <li><a class="dropdown-item4">Tabantha Wheat</a></li>
                </ul>
            </div>

            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Ingredient 4
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item1">Fortified Pumpkin</a></li>
                    <li><a class="dropdown-item2">Goat Butter</a></li>
                    <li><a class="dropdown-item3">Fresh Milk</a></li>
                    <li><a class="dropdown-item4">Tabantha Wheat</a></li>
                </ul>
            </div>

            <asp:button id="GetRecipe" onclick="GetRecipe_Click" runat="server" class="btn btn-secondary" type="button">Get Recipe</asp:button>
        </div>
    </div>
</div>

BOTWRecipeEngine/Views/Recipe/Index.cshtml
@model IEnumerable<BOTWRecipeEngine.Models.Botw_Recipes>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>Hello from our View Template!</p>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RecipeName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredient1)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredient2)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredient3)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredient4)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Num_Hearts)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RecipePicture)
                </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecipeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ingredient1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ingredient2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ingredient3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ingredient4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Num_Hearts)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecipePicture)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BOTWRecipeEngine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BOTWRecipeEngine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BOTWRecipeEngine.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="Index">Index</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BOTWRecipeEngine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>